#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.add_source_files(env.editor_sources, "core/interfaces/*.cpp")
env.add_source_files(env.editor_sources, "core/config/*.cpp")
env.add_source_files(env.editor_sources, "core/providers/*.cpp")
env.add_source_files(env.editor_sources, "core/orchestrator/*.cpp")
env.add_source_files(env.editor_sources, "core/context/*.cpp")
env.add_source_files(env.editor_sources, "runtime/*.cpp")
env.add_source_files(env.editor_sources, "ui/*.cpp")
